FROM mcr.microsoft.com/devcontainers/cpp

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y pkg-config cmake gcc g++ gdb doxygen autoconf autoconf-archive libtool libgtest-dev

#ENV DEBUGINFOD_URLS=https://debuginfod.ubuntu.com/