name: CMake workflow for libpwsafe

on: 
  push:
    branches: 
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup environment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake gcc g++ nettle-dev rpm
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE:STRING=Release -B build
    - name: build
      run: |
        cd build
        cmake --build . -t all
    - name: test
      run: |
        cd build
        ctest
    - name: package
      run: |
        cd build 
        cpack -G DEB
    - name: push release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
      with:
        files: build/*.deb
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
