name: CMake workflow for libpwsafe

on: 
  push:
    branches: 
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake gcc g++ doxygen
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake --preset=default
    - name: Build
      run: |
        cd build
        cmake --build . -t all
    - name: Test
      run: |
        cd build
        ctest
    - name: Package
      run: |
        cd build 
        cpack -G DEB
    - name: Push release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/*.deb
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
